# Generated by Django 3.0.8 on 2020-08-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20200803_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoholder',
            name='ran_id',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
