# Generated by Django 3.0.8 on 2020-08-03 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_todo_ran_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
        migrations.AlterField(
            model_name='todo',
            name='ran_id',
            field=models.CharField(default=uuid.UUID('250b9b7b-15ef-41fa-b5dd-d17ba47ec712'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
