# Generated by Django 3.0.8 on 2020-08-03 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20200803_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='ran_id',
            field=models.CharField(default=uuid.UUID('490a31eb-93e5-4f89-979a-37e1b6d14849'), max_length=20, primary_key=True, serialize=False),
        ),
    ]
