# Generated by Django 3.0.8 on 2020-08-03 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_auto_20200803_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='ran_id',
            field=models.CharField(default=uuid.UUID('f8024005-a06e-4d87-a115-cd97187eebe3'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
