# Generated by Django 3.0.8 on 2020-08-03 10:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_auto_20200803_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='ran_id',
            field=models.CharField(default=uuid.UUID('99e02d6f-966d-481a-a281-6eeb8df99a91'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
