# Generated by Django 3.0.8 on 2020-08-03 10:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_auto_20200803_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='ran_id',
            field=models.CharField(default=uuid.UUID('c70929ea-e7c5-483c-8499-8d9b7a7862a1'), max_length=50, primary_key=True, serialize=False),
        ),
    ]
