# Generated by Django 3.0.8 on 2020-08-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_auto_20200803_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='ran_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
